#!/usr/bin/env node
/*
 * Builds the downloadable zips under docs/assets/ from the unzipped sources
 * committed in the repo:
 *   - docs/assets/full_manual_repport_exp.zip  <- from example_vault/
 *   - docs/assets/mergdowntotex.zip            <- from mergdowntotex/  (release structure)
 *
 * Sources are committed UNZIPPED; the zips are generated by the CI
 * (scripts/build_assets.js) so nothing heavy is ever uploaded by hand.
 *
 * Usage:
 *   node scripts/build_assets.js          # -> both zips
 *   node scripts/build_assets.js --check  # verify each source folder and zip are in sync
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

/** [source dir, output zip, basenames to exclude, human label] */
const TARGETS = [
  {
    dir: "example_vault",
    out: "docs/assets/full_manual_repport_exp.zip",
    exclude: new Set(["data.json"]),
    label: "vault exemple",
  },
  {
    dir: "mergdowntotex",
    out: "docs/assets/mergdowntotex.zip",
    exclude: new Set(["data.json"]),
    label: "dossier release mergdowntotex",
  },
];

function run(args, opts) {
  return execFileSync(args[0], args.slice(1), { encoding: "utf8", cwd: ROOT, ...opts });
}

function collectFiles(dir, out, relPrefix, exclude) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = relPrefix ? `${relPrefix}/${ent.name}` : ent.name;
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      collectFiles(abs, out, rel, exclude);
    } else if (!exclude.has(ent.name)) {
      out.push(rel);
    }
  }
}

function buildTarget(target) {
  const srcDir = path.join(ROOT, target.dir);
  const outPath = path.join(ROOT, target.out);
  if (!fs.existsSync(srcDir)) {
    console.error(`❌ Dossier source introuvable : ${srcDir}`);
    process.exit(1);
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  const tmp = path.join(ROOT, `.tmp-${target.dir}.zip`);
  fs.rmSync(tmp, { force: true });
  const excludeArgs = [...target.exclude].flatMap((e) => ["-x", `*/${e}`]);
  run(["zip", "-q", "-r", "-X", tmp, ".", ...excludeArgs], { cwd: srcDir });
  fs.copyFileSync(tmp, outPath);
  fs.rmSync(tmp, { force: true });

  const files = [];
  collectFiles(srcDir, files, "", target.exclude);
  console.log(`✅ ${target.label} → ${target.out}`);
  console.log(`   ${files.length} fichiers, ${(fs.statSync(outPath).size / 1024 / 1024).toFixed(1)} Mo`);
}

function checkTarget(target) {
  const srcDir = path.join(ROOT, target.dir);
  const outPath = path.join(ROOT, target.out);
  if (!fs.existsSync(outPath)) {
    console.error(`❌ Zip absent : ${outPath}. Lancez d'abord : node scripts/build_assets.js`);
    process.exit(1);
  }
  const listing = run(["unzip", "-l", outPath]);
  const zipped = new Set(
    [...listing.matchAll(/^\s+\d+\s+[0-9-]+\s+[0-9:]+\s+(\S.*)$/gm)]
      .map((m) => m[1].trim())
      .filter((f) => f && !f.endsWith("/"))
  );
  const onDisk = [];
  collectFiles(srcDir, onDisk, "", target.exclude);
  const diskSet = new Set(onDisk);
  const missingFromZip = onDisk.filter((f) => !zipped.has(f));
  const extraInZip = [...zipped].filter((f) => !diskSet.has(f));
  if (missingFromZip.length || extraInZip.length) {
    console.error(`❌ Désynchronisation ${target.label}/zip :`);
    missingFromZip.forEach((f) => console.error(`   absent du zip: ${f}`));
    extraInZip.forEach((f) => console.error(`   en trop dans le zip: ${f}`));
    process.exit(1);
  }
  console.log(`✅ ${target.label} et le zip sont synchronisés.`);
}

const mode = process.argv.includes("--check") ? "check" : "build";
for (const target of TARGETS) {
  if (mode === "build") buildTarget(target);
  else checkTarget(target);
}