#!/usr/bin/env node
/*
 * Builds the downloadable zips under docs/assets/ from the unzipped sources
 * committed in the repo:
 *   - docs/assets/full_manual_repport_exp.zip  <- from example_vault/
 *   - docs/assets/mergdowntotex.zip            <- from mergdowntotex/  (release structure)
 *   - docs/assets/mergdowntotex_bundle.zip     <- plugin + vault exemple combinés (le "tout")
 *   - docs/assets/pandoc_wasm.zip              <- pandoc.wasm seul, comprimé (DOCX)
 *   - docs/assets/typst_wasm.zip               <- typst.wasm seul, comprimé (PDF)
 *   - docs/assets/typst_fonts.zip              <- les 17 polices typst, comprimées (PDF)
 *
 * Sources are committed UNZIPPED; the zips are generated by the CI
 * (scripts/build_assets.js) so nothing heavy is ever uploaded by hand.
 *
 * Usage:
 *   node scripts/build_assets.js                  # -> all zips
 *   node scripts/build_assets.js --only vlatex    # -> only the zip matching 'vlatex'
 *   node scripts/build_assets.js --check           # verify each source folder and zip are in sync
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

/**
 * [sources, output zip, basenames to exclude, human label]
 * sources: [{ dir, prefix }] — prefix = dossier dans le zip ("" = contenu à la racine).
 */
const TARGETS = [
  {
    sources: [{ dir: "example_vault", prefix: "" }],
    out: "docs/assets/full_manual_repport_exp.zip",
    // data.json du plugin D'EXEMPLE est un fichier de config PROPRE (valeurs
    // par défaut + pipeline WASM typst) : il doit être inclus pour qu'un NOUVEAU
    // vault soit pré-configuré. Le déploiement « dans le vault actuel » le
    // remplace aussi désormais (bouton « Télécharger le dossier d'exemple »).
    exclude: new Set([]),
    label: "vault exemple",
  },
  {
    sources: [{ dir: "mergdowntotex", prefix: "" }],
    out: "docs/assets/mergdowntotex.zip",
    exclude: new Set(["data.json"]),
    label: "dossier release mergdowntotex",
  },
  {
    sources: [
      { dir: "example_vault", prefix: "example_vault" },
      { dir: "mergdowntotex", prefix: "mergdowntotex" },
    ],
    out: "docs/assets/mergdowntotex_bundle.zip",
    // data.json inclus (pré-configuration du vault exemple dans le bundle) ;
    // la source mergdowntotex/ n'en contient pas, l'installation « plugin seul »
    // reste donc en réglages par défaut.
    exclude: new Set([]),
    label: "bundle plugin + vault exemple",
  },
  {
    // pandoc.wasm SEUL, COMPRESSÉ : téléchargement rapide sur mobile (~15 Mo au
    // lieu de ~59 Mo), nécessaire UNIQUEMENT pour l'export DOCX.
    sources: [{ dir: path.join("mergdowntotex", "wasm"), prefix: "", include: /^pandoc\.wasm$/ }],
    out: "docs/assets/pandoc_wasm.zip",
    exclude: new Set([]),
    label: "bundle WASM pandoc seul (compressé)",
    compress: true, // compression maximale pour réduire la taille du téléchargement
  },
  {
    // typst.wasm SEUL, COMPRESSÉ : téléchargement rapide sur mobile (~10 Mo au
    // lieu de ~28 Mo), nécessaire UNIQUEMENT pour l'export PDF.
    sources: [{ dir: path.join("mergdowntotex", "wasm"), prefix: "", include: /^typst\.wasm$/ }],
    out: "docs/assets/typst_wasm.zip",
    exclude: new Set([]),
    label: "bundle WASM typst seul (compressé)",
    compress: true, // compression maximale pour réduire la taille du téléchargement
  },
  {
    // Les 17 POLICES typst, séparées du wasm (ni pandoc ni typst n'en ont besoin
    // pour compiler ; elles ne servent qu'au rendu PDF). Compression max.
    sources: [{ dir: path.join("mergdowntotex", "wasm"), prefix: "", include: /^fonts\// }],
    out: "docs/assets/typst_fonts.zip",
    exclude: new Set([]),
    label: "bundle polices typst (compressé)",
    compress: true, // compression maximale pour réduire la taille du téléchargement
  },
  {
    // vlatex.wasm SEUL, COMPRESSÉ : le moteur vLaTeX (transformations md→tex,
    // filtre DOCX, bibliographie) qui avait disparu des releases ; ~0,9 Mo.
    sources: [{ dir: path.join("mergdowntotex", "wasm"), prefix: "", include: /^vlatex\.wasm$/ }],
    out: "docs/assets/vlatex_wasm.zip",
    exclude: new Set([]),
    label: "bundle WASM vLaTeX seul (compressé)",
    compress: true, // compression maximale pour réduire la taille du téléchargement
  },
];

// Vérifie si une entrée (chemin relatif, en incluant le préfixe éventuel) doit
// être retenue d'après la règle `include` de la source. Les dossiers sont testés
// avec un "/" final pour permettre des includes de type `fonts/`.
function includeOk(src, rel) {
  if (!src.include) return true;
  const test = (x) => (src.include instanceof RegExp ? src.include.test(x) : x === src.include);
  return test(rel) || test(rel + "/");
}

function copyDirRec(srcAbs, destAbs) {
  fs.mkdirSync(destAbs, { recursive: true });
  for (const ent of fs.readdirSync(srcAbs, { withFileTypes: true })) {
    const s = path.join(srcAbs, ent.name);
    const d = path.join(destAbs, ent.name);
    if (ent.isDirectory()) copyDirRec(s, d);
    else fs.copyFileSync(s, d);
  }
}

function run(args, opts) {
  return execFileSync(args[0], args.slice(1), { encoding: "utf8", cwd: ROOT, ...opts });
}

function collectSource(src, out, exclude) {
  const dir = path.join(ROOT, src.dir);
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = ent.name;
    const abs = path.join(dir, ent.name);
    const prefixed = src.prefix ? `${src.prefix}/${rel}` : rel;
    if (ent.isDirectory()) {
      if (includeOk(src, prefixed)) collectDir(abs, out, prefixed, exclude, src);
    } else if (!exclude.has(ent.name)) {
      if (includeOk(src, prefixed)) out.push(prefixed);
    }
  }
}

function collectDir(dir, out, relPrefix, exclude, src) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = relPrefix ? `${relPrefix}/${ent.name}` : ent.name;
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      if (includeOk(src, rel)) collectDir(abs, out, rel, exclude, src);
    } else if (!exclude.has(ent.name)) {
      if (includeOk(src, rel)) out.push(rel);
    }
  }
}

function collectTarget(target) {
  const files = [];
  for (const src of target.sources) collectSource(src, files, target.exclude);
  return files;
}

function buildTarget(target) {
  const outPath = path.join(ROOT, target.out);
  for (const src of target.sources) {
    if (!fs.existsSync(path.join(ROOT, src.dir))) {
      console.error(`❌ Dossier source introuvable : ${src.dir}`);
      process.exit(1);
    }
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  const tmp = path.join(ROOT, `.tmp-${target.out.replace(/\W+/g, "-")}`);
  fs.rmSync(tmp, { force: true });

  // Zip tous les dossiers sources (depuis ROOT). Préfixe "" => on zippe le contenu
  // du dossier ; sinon on zippe le dossier avec son nom comme racine. Si une
  // source a une règle `include`, on ne zippe QUE les fichiers sélectionnés
  // (staging dans un dossier temporaire pour préserver la structure).
  const excludeArgs = [...target.exclude].flatMap((e) => ["-x", `*/${e}`]);
  const lvlArgs = target.compress ? ["-9"] : [];
  for (const src of target.sources) {
    if (src.prefix) {
      // dossier complet, zippé sous son propre nom
      run(["zip", "-q", "-r", "-X", ...lvlArgs, tmp, src.dir, ...excludeArgs]);
    } else if (src.include) {
      // sous-ensemble sélectionné : on copie uniquement les fichiers inclus
      // dans un dossier de staging, puis on zippe le contenu de ce dossier.
      const stage = path.join(ROOT, `.stage-${target.out.replace(/\W+/g, "-")}`);
      fs.rmSync(stage, { recursive: true, force: true });
      fs.mkdirSync(stage, { recursive: true });
      stageSource(src, stage, target.exclude);
      run(["zip", "-q", "-r", "-X", ...lvlArgs, tmp, ".", ...excludeArgs], { cwd: stage });
      fs.rmSync(stage, { recursive: true, force: true });
    } else {
      // contenu du dossier à la racine du zip
      run(["zip", "-q", "-r", "-X", ...lvlArgs, tmp, ".", ...excludeArgs], { cwd: path.join(ROOT, src.dir) });
    }
  }
  fs.copyFileSync(tmp, outPath);
  fs.rmSync(tmp, { force: true });

  const files = collectTarget(target);
  console.log(`✅ ${target.label} → ${target.out}`);
  console.log(`   ${files.length} fichiers, ${(fs.statSync(outPath).size / 1024 / 1024).toFixed(1)} Mo`);
}

// Copie dans `stage` uniquement les fichiers retenus par la règle `include` de la
// source, en préservant la structure relative (fonts/…).
function stageSource(src, stage, exclude) {
  const dir = path.join(ROOT, src.dir);
  const walk = (relDir) => {
    for (const ent of fs.readdirSync(path.join(dir, relDir), { withFileTypes: true })) {
      const rel = relDir ? `${relDir}/${ent.name}` : ent.name;
      const abs = path.join(dir, rel);
      if (ent.isDirectory()) {
        if (includeOk(src, rel)) copyDirRec(abs, path.join(stage, rel));
        else walk(rel);
      } else {
        if (exclude.has(ent.name)) continue;
        if (includeOk(src, rel)) {
          const dest = path.join(stage, rel);
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.copyFileSync(abs, dest);
        }
      }
    }
  };
  walk("");
}

function checkTarget(target) {
  const outPath = path.join(ROOT, target.out);
  if (!fs.existsSync(outPath)) {
    console.error(`❌ Zip absent : ${outPath}. Lancez d'abord : node scripts/build_assets.js`);
    process.exit(1);
  }
  const listing = run(["unzip", "-l", outPath]);
  const zipped = new Set(
    [...listing.matchAll(/^\s+\d+\s+[0-9-]+\s+[0-9:]+\s+(\S.*)$/gm)]
      .map((m) => m[1].trim())
      .filter((f) => f && !f.endsWith("/"))
  );
  const onDisk = collectTarget(target);
  const diskSet = new Set(onDisk);
  const missingFromZip = onDisk.filter((f) => !zipped.has(f));
  const extraInZip = [...zipped].filter((f) => !diskSet.has(f));
  if (missingFromZip.length || extraInZip.length) {
    console.error(`❌ Désynchronisation ${target.label}/zip :`);
    missingFromZip.forEach((f) => console.error(`   absent du zip: ${f}`));
    extraInZip.forEach((f) => console.error(`   en trop dans le zip: ${f}`));
    process.exit(1);
  }
  console.log(`✅ ${target.label} et le zip sont synchronisés.`);
}

const mode = process.argv.includes("--check") ? "check" : "build";
const onlyIdx = process.argv.indexOf("--only");
const only = onlyIdx >= 0 ? process.argv[onlyIdx + 1] : null;
for (const target of TARGETS) {
  if (only && !target.out.includes(only) && target.label.indexOf(only) < 0) continue;
  if (mode === "build") buildTarget(target);
  else checkTarget(target);
}