#!/usr/bin/env node
/*
 * Builds the downloadable zips under docs/assets/ from the unzipped sources
 * committed in the repo:
 *   - docs/assets/full_manual_repport_exp.zip  <- from example_vault/
 *   - docs/assets/mergdowntotex.zip            <- from mergdowntotex/  (release structure)
 *   - docs/assets/mergdowntotex_bundle.zip     <- plugin + vault exemple combinés (le "tout")
 *
 * Sources are committed UNZIPPED; the zips are generated by the CI
 * (scripts/build_assets.js) so nothing heavy is ever uploaded by hand.
 *
 * Usage:
 *   node scripts/build_assets.js          # -> all zips
 *   node scripts/build_assets.js --check  # verify each source folder and zip are in sync
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");

/**
 * [sources, output zip, basenames to exclude, human label]
 * sources: [{ dir, prefix }] — prefix = dossier dans le zip ("" = contenu à la racine).
 */
const TARGETS = [
  {
    sources: [{ dir: "example_vault", prefix: "" }],
    out: "docs/assets/full_manual_repport_exp.zip",
    exclude: new Set(["data.json"]),
    label: "vault exemple",
  },
  {
    sources: [{ dir: "mergdowntotex", prefix: "" }],
    out: "docs/assets/mergdowntotex.zip",
    exclude: new Set(["data.json"]),
    label: "dossier release mergdowntotex",
  },
  {
    sources: [
      { dir: "example_vault", prefix: "example_vault" },
      { dir: "mergdowntotex", prefix: "mergdowntotex" },
    ],
    out: "docs/assets/mergdowntotex_bundle.zip",
    exclude: new Set(["data.json"]),
    label: "bundle plugin + vault exemple",
  },
  {
    // Tout le dossier wasm/ (pandoc.wasm, typst.wasm, fonts/) COMPRESSÉ en un
    // seul zip pour un téléchargement rapide sur mobile (97 Mo → ~34 Mo).
    // Le contenu est à la racine du zip (pandoc.wasm, typst.wasm, fonts/...).
    sources: [{ dir: path.join("mergdowntotex", "wasm"), prefix: "" }],
    out: "docs/assets/wasm_bundle.zip",
    exclude: new Set([]),
    label: "bundle WASM (pandoc+typst+fonts, compressés)",
    compress: true, // compression maximale pour réduire la taille du téléchargement
  },
];

function run(args, opts) {
  return execFileSync(args[0], args.slice(1), { encoding: "utf8", cwd: ROOT, ...opts });
}

function collectSource(src, out, exclude) {
  const dir = path.join(ROOT, src.dir);
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = ent.name;
    const abs = path.join(dir, ent.name);
    const prefixed = src.prefix ? `${src.prefix}/${rel}` : rel;
    if (ent.isDirectory()) {
      collectDir(abs, out, prefixed, exclude);
    } else if (!exclude.has(ent.name)) {
      out.push(prefixed);
    }
  }
}

function collectDir(dir, out, relPrefix, exclude) {
  for (const ent of fs.readdirSync(dir, { withFileTypes: true })) {
    const rel = relPrefix ? `${relPrefix}/${ent.name}` : ent.name;
    const abs = path.join(dir, ent.name);
    if (ent.isDirectory()) {
      collectDir(abs, out, rel, exclude);
    } else if (!exclude.has(ent.name)) {
      out.push(rel);
    }
  }
}

function collectTarget(target) {
  const files = [];
  for (const src of target.sources) collectSource(src, files, target.exclude);
  return files;
}

function buildTarget(target) {
  const outPath = path.join(ROOT, target.out);
  for (const src of target.sources) {
    if (!fs.existsSync(path.join(ROOT, src.dir))) {
      console.error(`❌ Dossier source introuvable : ${src.dir}`);
      process.exit(1);
    }
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });

  const tmp = path.join(ROOT, `.tmp-${target.out.replace(/\W+/g, "-")}`);
  fs.rmSync(tmp, { force: true });

  // Zip tous les dossiers sources (depuis ROOT). Préfixe "" => on zippe le contenu
  // du dossier ; sinon on zippe le dossier avec son nom comme racine.
  const excludeArgs = [...target.exclude].flatMap((e) => ["-x", `*/${e}`]);
  const names = target.sources.map((src) => (src.prefix ? src.prefix : `${src.dir}/*`));
  const lvlArgs = target.compress ? ["-9"] : [];
  for (const src of target.sources) {
    if (src.prefix) {
      // dossier complet, zippé sous son propre nom
      run(["zip", "-q", "-r", "-X", ...lvlArgs, tmp, src.dir, ...excludeArgs]);
    } else {
      // contenu du dossier à la racine du zip
      run(["zip", "-q", "-r", "-X", ...lvlArgs, tmp, ".", ...excludeArgs], { cwd: path.join(ROOT, src.dir) });
    }
  }
  fs.copyFileSync(tmp, outPath);
  fs.rmSync(tmp, { force: true });

  const files = collectTarget(target);
  console.log(`✅ ${target.label} → ${target.out}`);
  console.log(`   ${files.length} fichiers, ${(fs.statSync(outPath).size / 1024 / 1024).toFixed(1)} Mo`);
}

function checkTarget(target) {
  const outPath = path.join(ROOT, target.out);
  if (!fs.existsSync(outPath)) {
    console.error(`❌ Zip absent : ${outPath}. Lancez d'abord : node scripts/build_assets.js`);
    process.exit(1);
  }
  const listing = run(["unzip", "-l", outPath]);
  const zipped = new Set(
    [...listing.matchAll(/^\s+\d+\s+[0-9-]+\s+[0-9:]+\s+(\S.*)$/gm)]
      .map((m) => m[1].trim())
      .filter((f) => f && !f.endsWith("/"))
  );
  const onDisk = collectTarget(target);
  const diskSet = new Set(onDisk);
  const missingFromZip = onDisk.filter((f) => !zipped.has(f));
  const extraInZip = [...zipped].filter((f) => !diskSet.has(f));
  if (missingFromZip.length || extraInZip.length) {
    console.error(`❌ Désynchronisation ${target.label}/zip :`);
    missingFromZip.forEach((f) => console.error(`   absent du zip: ${f}`));
    extraInZip.forEach((f) => console.error(`   en trop dans le zip: ${f}`));
    process.exit(1);
  }
  console.log(`✅ ${target.label} et le zip sont synchronisés.`);
}

const mode = process.argv.includes("--check") ? "check" : "build";
for (const target of TARGETS) {
  if (mode === "build") buildTarget(target);
  else checkTarget(target);
}